circuit-build:
  cd circuit && nargo execute


write-vk:
  cd circuit && bb write_vk --oracle_hash keccak -o target -b target/hello_world.json


build-contract:
  cd contracts && cargo build --release --target wasm32-unknown-unknown

deploy-contract:
  cd contracts && cargo stylus deploy -e "http://localhost:8547" --private-key "0xb6b15c8cb491557369f3c7d2c287b053eb229daa9c22138887752191c9520659" --verbose --no-verify --constructor-args "0x2f9f4741ab606632718f7bda0bf5c79e1dd03ac3"

verify-global:
  node scripts/verify-global.js

verify:
  node scripts/verify.js

prove:
  cd circuit && bb prove -b ./target/hello_world.json -w ./target/hello_world.gz -o ./target --scheme ultra_honk --oracle_hash keccak