name: Build CLI

on:
  push:
    branches:
      - develop
    tags-ignore:
      - v*
  pull_request:

env:
  # incremental builds are slower and don't make much sense in ci
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: FULL

jobs:
  build:
    name: Build CLI
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            build_command: cargo build --release --target=x86_64-unknown-linux-musl -p nsv
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            build_command: cargo build --release --target=x86_64-pc-windows-msvc -p nsv
          - os: macos-latest
            target: x86_64-apple-darwin
            build_command: cargo build --release --target=x86_64-apple-darwin -p nsv

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-06-12

      - name: Install Build Target
        run: rustup target add ${{ matrix.target }} --toolchain nightly-2025-06-12

      - uses: Swatinem/rust-cache@v2

      - name: Install build tools (Linux only)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc lld

      - name: Install build tools (macOS only)
        if: runner.os == 'macOS'
        run: brew install llvm

      - name: Build CLI
        run: ${{ matrix.build_command }}
