name: Integration Tests
permissions:
  contents: read
on:
  push:
    branches:
      - develop
    tags-ignore:
      - v*
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  CARGO_TERM_COLOR: always
jobs:
  required:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/workflows/rust-setup.yml
      
      - name: Install cargo-stylus
        run: cargo install cargo-stylus@0.6.0

      - uses: extractions/setup-just@v3
        with:
          just-version: 1.38.0 

      - name: Setup nitro node
        run: just nitro-testnode-up

      - name: Run integration tests
        run: just test-integration

      - name: Shutdown nitro node
        run: just nitro-testnode-down