name: Rust Lints

on:
  push:
    branches:
      - develop
    tags-ignore:
      - v*
  pull_request:

env:
  # incremental builds are slower and don't make much sense in ci
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: FULL

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-06-12
          components: rustfmt, clippy

      - uses: extractions/setup-just@v3
        with:
          just-version: 1.38.0 

      - name: Check fmt issues
        run: just fmt

      - name: Check lint issues
        run: just lint
      