name: Rust Build

on:
  push:
    branches:
      - develop
    tags-ignore:
      - v*
  pull_request:

env:
  # incremental builds are slower and don't make much sense in ci
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: FULL
  RUSTFLAGS: "-C link-arg=-fuse-ld=lld"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: sudo apt-get install lld
      - uses: Swatinem/rust-cache@v2
      - name: Build ultrahonk 
        run: cargo build -p ultrahonk --profile ci-dev --all-features
      - name: Build contracts 
        run: cargo build -p contracts --target wasm32-unknown-unknown --profile ci-dev
