name: Build Contracts

on:
  push:
    branches:
      - develop
    tags-ignore:
      - v*
  pull_request:

env:
  # incremental builds are slower and don't make much sense in ci
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: FULL

jobs:
  build:
    name: Build Contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly-2025-06-12

      - name: Add rust-src component
        run: rustup component add rust-src --toolchain nightly-2025-06-12

      - name: Install Build Targets
        run: rustup target add wasm32-unknown-unknown --toolchain nightly-2025-06-12

      - uses: Swatinem/rust-cache@v2

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential gcc lld

      - name: Install just
        uses: extractions/setup-just@v3
        with:
          just-version: 1.38.0 
  
      - name: Build Sumcheck Verifier contract
        run: just build-contract sumcheck-verifier

      - name: Build Shplemini Verifier contract
        run: just build-contract shplemini-verifier

      - name: Build Verifier contract
        run: just build-contract verifier

      - name: Build Zk Sumcheck Verifier contract
        run: just build-contract zk-sumcheck-verifier

      - name: Build Zk Shplemini Verifier contract
        run: just build-contract zk-shplemini-verifier

      - name: Build Zk Verifier contract
        run: just build-contract zk-verifier
