name: Build Contracts

on:
  push:
    branches:
      - develop
    tags-ignore:
      - v*
  pull_request:

env:
  # incremental builds are slower and don't make much sense in ci
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: FULL

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: .github/workflows/rust-setup.yml

      - uses: extractions/setup-just@v3
        with:
          just-version: 1.38.0 

      - name: Build Sumcheck Verifier contract
        run: just build-contract sumcheck-verifier

      - name: Build Shplemini Verifier contract
        run: just build-contract shplemini-verifier

      - name: Build Verifier contract
        run: just build-contract verifier
