# off until ultrahonk package is fully compatible with stylus
name: Stylus Check

on:
  push:
    branches:
      - develop
    tags-ignore:
      - v*
  pull_request:

env:
  # incremental builds are slower and don't make much sense in ci
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: FULL

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: .github/workflows/rust-setup.yml

      - name: Install cargo-stylus
        run: cargo install cargo-stylus@0.6.0

      - uses: extractions/setup-just@v3
        with:
          just-version: 1.38.0 

      - name: Check Verifier contract
        run: just --set rpc_url https://sepolia-rollup.arbitrum.io/rpc check-contract verifier

      - name: Check Sumcheck Verifier contract
        run: just --set rpc_url https://sepolia-rollup.arbitrum.io/rpc check-contract sumcheck-verifier

      - name: Check Shplemini Verifier contract
        run: just --set rpc_url https://sepolia-rollup.arbitrum.io/rpc check-contract shplemini-verifier
